flyway.cleanDisabled=${DEV_CLEAN_DISABLED}
flyway.url=${DEV_URL}
flyway.user=${DEV_USER}
flyway.password=${DEV_PASSWORD}
flyway.locations=${DEV_LOCATIONS}
flyway.schemas=${DEV_SCHEMAS}
flyway.defaultSchema=${DEV_DEFAULT_SCHEMA}
flyway.createSchemas=${DEV_CREATE_SCHEMAS}